# Gunakan base image Alpine Linux versi 3.20
FROM alpine:3.20

# Tambahkan curl
RUN apk --no-cache add curl

# Set working directory
WORKDIR /home/

# Copy source code into the container
COPY src/hit_api.sh .

# Beri izin eksekusi pada skrip
RUN chmod +x hit_api.sh

# Jalankan skrip saat container dimulai
ENTRYPOINT ["/home/hit_api.sh"]
