# Gunakan base image Alpine Linux versi 3.20
FROM alpine:3.20

# Install supervisor dan curl
RUN apk --no-cache add supervisor curl

# Set working directory
WORKDIR /home/

# Copy source code into the container
COPY src/hit_api.sh .

# Beri izin eksekusi pada skrip
RUN chmod +x /home/hit_api.sh

# Trigger supervisor
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
