# Gunakan base image Alpine Linux versi 3.20
FROM alpine:3.20

# Tambahkan curl
RUN apk --no-cache add curl

# Set working directory
WORKDIR /home/

# Copy source code into the container
COPY src/hit_api.sh .

# Beri izin eksekusi pada skrip
RUN chmod +x /home/hit_api.sh

# Debugging: List isi direktori untuk memastikan file ada
RUN ls -l /home/

# Jalankan skrip saat container dimulai
ENTRYPOINT ["sh /home/hit_api.sh"]
